Decoder:
  channel_factor: 32
  z_dim: 64
  upsample_s: [2, 2]
  upsample_t: [2, 1]
  spectral_norm: True

Encoder:
  res_type_encoder: 'resnet18'
  deterministic: false
  use_max_pool: false
  z_dim: 64
  channels: [64, 128, 128, 256, 512]
  stride_t: [1, 2, 2, 2]
  stride_s: [2, 2, 2, 2]

Discriminator_Temporal:
  eval_seq_length: 16
  res_type_encoder: 'resnet18'
  deterministic: false
  use_max_pool: true
  channels: [64, 64, 128, 256, 512]
  stride_t: [2, 2, 2, 2]
  stride_s: [1, 2, 2, 2]
  spectral_norm: True

Discriminator_Patch:
  in_channels: 3
  ndf: 64
  n_layers: 3
  use_actnorm: True
  spectral_norm: True

Training:
  GAN_Loss: 'hinge'
  w_coup_s: 1
  w_coup_t: 1
  w_fmap_t: 10
  w_percep: 30
  w_recon: 20
  w_GP: 10
  w_kl: 1e-6
  subsample_length: 12
  pretrain: 1
  n_epochs: 100
  lr: 2e-4
  workers: 14
  bs: 7
  bs_eval: 10
  verbose_idx: 30
  weight_decay: 1e-5
  lr_gamma: 0.98
  FVD: 'DTFVD'
  savename: 'INSERT_NAME_HERE'
  save_path: 'INSERT_PATH_HERE'
  reload_path: ''

Data:
  sequence_length: 17
  img_size: 128
  dataset: 'landscape'
  aug: True
  iter_train: 10
  iter_eval: 7
  iter_test: 6
  data_path: 'INSERT_DATA_PATH_HERE'
  Augmentation:
    brightness: 0.3
    contrast: 0.3
    saturation: 0.3
    hue: 0.15
    prob_hflip: 0.5

Logging:
  entity: 'INSERT_WANDB_NAME'
  project: "INSERT_PROJECT_NAME"
  mode: 'online'

